### ISSUE TITLE
how do i use it in vencord

### ISSUE THREAD

**Issue by Bst69** [UserPFP/UserPFP#10]
there's no plugin like this in vencord

**Comment by cutekita** [comment]
we made a plugin for it and its all done but vendicated doesn't feel like adding it, there's no reason behind it, except for disliking me probably. use Equicord/Equicord instead or load our import.css file using Quickcss

**Comment by cutekita** [comment]
`@import url(https://raw.githubusercontent.com/UserPFP/UserPFP/main/import.css);`

is what you need to paste on top of your QuickCSS if you want to stay on vencord
